#ifndef MINIASM_DIRECTIVES_H
#define MINIASM_DIRECTIVES_H

#include <stdbool.h>

typedef enum {
	DIRECTIVE_DB,
	DIRECTIVE_DW,
	DIRECTIVE_DD,
	DIRECTIVE_MOVI,
	DIRECTIVE_NULL,
	DIRECTIVE_TIMES_SIZE,
	DIRECTIVE_TIMES,
	DIRECTIVE_LABEL,
	DIRECTIVE_LABELDEF,
	DIRECTIVE_ADD,
	DIRECTIVE_SUB,
	DIRECTIVE_OR,
	DIRECTIVE_AND,
	DIRECTIVE_ADC,
	DIRECTIVE_SBB,
	DIRECTIVE_XOR,
	DIRECTIVE_CMP,
	DIRECTIVE_MUL,
	DIRECTIVE_IMUL,
	DIRECTIVE_DIV,
	DIRECTIVE_IDIV,
	DIRECTIVE_SHL,
	DIRECTIVE_SHR,
	DIRECTIVE_SAR,
	DIRECTIVE_ROL,
	DIRECTIVE_ROR,
	DIRECTIVE_NOT,
	DIRECTIVE_NEG,
	DIRECTIVE_HLT,
	DIRECTIVE_INT,
	DIRECTIVE_STI,
	DIRECTIVE_CLI,
	DIRECTIVE_PUSH,
	DIRECTIVE_POP,
	DIRECTIVE_LOAX,
	DIRECTIVE_LOAX6,
	DIRECTIVE_LOAX8,
	DIRECTIVE_PUSHA,
	DIRECTIVE_POPA,
	DIRECTIVE_RET,
	DIRECTIVE_IRET,
	DIRECTIVE_CALL,
	DIRECTIVE_JMP,
	DIRECTIVE_RCALL,
	DIRECTIVE_RJMP,
} directive;

directive WtfDirectiveIs(const char *string, size_t *pos);
bool isPattern(const char *string, const char *pattern);

#endif
